package DataStructureAndAlgorithms.menus;

public enum MenuKey {
    EXIT,
    RETURN,

    RUN_PROBLEMS,
    CREATE_PROBLEM,
    MANAGE_PRACTICES,

    LIST_ALL_PROBLEMS,
    LIST_PROBLEMS_BY_CATEGORY,
    FIND_SPECIFIC_PROBLEM,

    CREATE_PRACTICE,
    RESET_PRACTICE,

    LIST_ALL_PRACTICES,
    LIST_PRACTICES_BY_CATEGORY,
    FIND_SPECIFIC_PRACTICE,
}
