package DataStructureAndAlgorithms.menus;

public enum MenuKey {
    EXIT,
    RETURN,

    RUN_PROBLEMS,
    CREATE_PROBLEM,
    MANAGE_PRACTICES,

    LIST_ALL_PROBLEMS,
    LIST_PROBLEMS_BY_CATEGORY,
    RUN_PROBLEM_BY_NAME,

    CREATE_PRACTICE,
    RESET_PRACTICE,

    LIST_ALL_PRACTICES,
    LIST_PRACTICES_BY_CATEGORY,
    RUN_PRACTICE_BY_NAME,

    FIND_SPECIFIC_PROBLEM;
}
