package DataStructureAndAlgorithms.menus;

public enum MenuKey {
    EXIT,
    RETURN,

    RUN_PROBLEMS,
    CREATE_PROBLEM,
    MANAGE_PRACTICES,

    LIST_ALL_PROBLEMS,
    LIST_PROBLEMS_BY_CATEGORY,
    FIND_SPECIFIC_PROBLEM,

    CREATE_PRACTICE,
    RESET_PRACTICE,
    BULK_RESET_PRACTICES,

    LIST_ALL_PRACTICES,
    LIST_PRACTICES_BY_CATEGORY,
    FIND_SPECIFIC_PRACTICE,

    RESET_ALL_PRACTICES,
    RESET_PRACTICES_BY_CATEGORY,

    RESET_EASY_PRACTICES,
    RESET_MEDIUM_PRACTICES,
    RESET_HARD_PRACTICES,
}
